INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('11111111101', 'a@a.com', 'João Queiroz Silva', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('11111111102', 'a@a.com', 'Maria Pereira Souza', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('11111111103', 'a@a.com', 'José Alves', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('11111111104', 'a@a.com', 'Julia Pereira Gonçalves', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('11111111105', 'a@a.com', 'Mário José França', '1234', true);

INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('22222222201', 'a@a.com', 'Mayara Barros Melo', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('22222222202', 'a@a.com', 'Francisco Santos Alves', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('22222222203', 'a@a.com', 'Juliana Pinheiro', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('22222222204', 'a@a.com', 'João Marcos Sampaio', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('22222222205', 'a@a.com', 'Helena Siqueira', '1234', true);

INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333300', 'a@a.com', 'André Barbosa Lima', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333301', 'a@a.com', 'Mariana Lima', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333302', 'a@a.com', 'Guilherme Tavares', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333303', 'a@a.com', 'Débora Lima Alves', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333304', 'a@a.com', 'Sávio Cavalcante', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333305', 'a@a.com', 'João Victor Gonçalves', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333306', 'a@a.com', 'Maria Adriana Alves', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333307', 'a@a.com', 'Joel Silveira', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333308', 'a@a.com', 'Bruna Nogueira', '1234', true);
INSERT INTO pessoa(cpf, email, nome, senha, habilitado) VALUES ('33333333309', 'a@a.com', 'João Pedro Almeida', '1234', true);

INSERT INTO servidor(pessoa_id) VALUES (1);
INSERT INTO servidor(pessoa_id) VALUES (2);
INSERT INTO servidor(pessoa_id) VALUES (3);
INSERT INTO servidor(pessoa_id) VALUES (4);
INSERT INTO servidor(pessoa_id) VALUES (5);
INSERT INTO servidor(pessoa_id) VALUES (6);
INSERT INTO servidor(pessoa_id) VALUES (7);
INSERT INTO servidor(pessoa_id) VALUES (8);
INSERT INTO servidor(pessoa_id) VALUES (9);
INSERT INTO servidor(pessoa_id) VALUES (10);

INSERT INTO aluno(pessoa_id) VALUES (11);
INSERT INTO aluno(pessoa_id) VALUES (12);
INSERT INTO aluno(pessoa_id) VALUES (13);
INSERT INTO aluno(pessoa_id) VALUES (14);
INSERT INTO aluno(pessoa_id) VALUES (15);
INSERT INTO aluno(pessoa_id) VALUES (16);
INSERT INTO aluno(pessoa_id) VALUES (17);
INSERT INTO aluno(pessoa_id) VALUES (18);
INSERT INTO aluno(pessoa_id) VALUES (19);
INSERT INTO aluno(pessoa_id) VALUES (20);

INSERT INTO papel_usuario(pessoa_id, papel) VALUES (1, 'COORDENADOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (1, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (2, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (3, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (4, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (5, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (6, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (7, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (8, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (9, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (10, 'SERVIDOR');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (11, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (12, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (13, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (14, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (15, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (16, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (17, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (18, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (19, 'ALUNO');
INSERT INTO papel_usuario(pessoa_id, papel) VALUES (20, 'ALUNO');